### ISSUE TITLE
ㄴㄴㅇㅇ

### ISSUE THREAD

**Issue by cute772** [lamact/react-issue-ganttchart#101]
```yaml
start_date: 2023/9/5
due_date: 2023/9/5
progress: 0.1
parent: 0
```
