### ISSUE TITLE
Tempo

### ISSUE THREAD

**Issue by johnhaverh** [lamact/react-issue-ganttchart#103]
```yaml
start_date: 2023/11/1
due_date: 2023/11/1
progress: 0.1
parent: 0
```
