### ISSUE TITLE
teste

### ISSUE THREAD

**Issue by alexandrevelozo** [lamact/react-issue-ganttchart#108]
```yaml
start_date: 2024/10/16
due_date: 2024/10/16
progress: 0.1
parent: 0
```
