### ISSUE TITLE
依存関係のリンクを追加

### ISSUE THREAD

**Issue by yhzz** [lamact/react-issue-ganttchart#15]
```yaml
start_date: 2021/2/26
due_date: 2021/3/5
progress: 1
parent: 0
dependon:
  - '46'
```
