### ISSUE TITLE
親子タスク

### ISSUE THREAD

**Issue by yhzz** [lamact/react-issue-ganttchart#17]
```yaml
start_date: 2021/2/12
due_date: 2021/2/15
progress: 1
parent: 0
```
### 親子関係
a
