### ISSUE TITLE
QuickInfoで説明欄をポップアップする

### ISSUE THREAD

**Issue by yhzz** [lamact/react-issue-ganttchart#29]
```yaml
start_date: 2021/2/7
due_date: 2021/2/12
progress: 1
parent: 0
```

## QuickInfo
https://docs.dhtmlx.com/gantt/desktop__quick_info.html
