### ISSUE TITLE
Issueの開始・終了日を変更すると画面遷移する

### ISSUE THREAD

**Issue by sakiko-k** [lamact/react-issue-ganttchart#32]
```yaml
start_date: 2021/2/9
due_date: 2021/2/17
progress: 1
parent: 0
```
