### ISSUE TITLE
Assigneeが4つしか選べない

### ISSUE THREAD

**Issue by sakiko-k** [lamact/react-issue-ganttchart#33]
```yaml
start_date: 2021/1/27
due_date: 2021/2/9
progress: 0.96
parent: 0
```

全てのAssigneeが出力され、なおかつ複数選択できると嬉しい。
