### ISSUE TITLE
横フリックに対応する

### ISSUE THREAD

**Issue by jtky8238** [lamact/react-issue-ganttchart#37]
```yaml
start_date: 2021/2/20
due_date: 2021/2/26
progress: 0.64
parent: 0
```

横フリック入力で
ガントチャートの日付部分を横にスクロールできるようにする．
