### ISSUE TITLE
【保留】マウスホイールで日付の表示レンジを変更

### ISSUE THREAD

**Issue by jtky8238** [lamact/react-issue-ganttchart#38]
```yaml
start_date: 2021/4/18
due_date: 2021/4/25
progress: 0.44
parent: 0
```

下記サンプルのような，マウスホイールで日付のレンジを変更できるようにしたい
https://docs.dhtmlx.com/gantt/samples/03_scales/14_scale_zoom_by_wheelmouse.html

Gantt.js  の　gantt.ext.zoom.init(zoom_config);　に挿入している設定
zoom_configをサンプルと同じにしたが，動作しなかったため
実装工数が膨らみそうなことから，優先度を下げる
