### ISSUE TITLE
画面に表示される未来日が少ない

### ISSUE THREAD

**Issue by sakiko-k** [lamact/react-issue-ganttchart#42]
```yaml
start_date: 2021/2/17
due_date: 2021/2/18
progress: 0
parent: 0
```
画面に表示される未来日が現在発生しているIssueの中で
最も遅い期限日までしか表示されない。
（画面上で期限を延長する際に不便）
