### ISSUE TITLE
labelリストにすべてのlabelが表示されない

### ISSUE THREAD

**Issue by sakiko-k** [lamact/react-issue-ganttchart#43]
```yaml
start_date: 2021/2/17
due_date: 2021/2/21
progress: 0.93
parent: 0
```
filter by labelsを押下して出力されるlabelのリストにすべてのlabelが表示されない
