### ISSUE TITLE
期限切れに関する文字変更

### ISSUE THREAD

**Issue by ktsg-lamact** [lamact/react-issue-ganttchart#45]
```yaml
start_date: 2021/2/15
due_date: 2021/2/20
progress: 1
parent: 0
```
