### ISSUE TITLE
Demo Site maintainance

### ISSUE THREAD

**Issue by jtky8238** [lamact/react-issue-ganttchart#53]
```yaml
start_date: 2021/4/23
due_date: 2021/5/4
progress: 1
parent: 0
dependon:
  - '15'
  - '47'
  - '38'
```

右上に赤字のエラーが出るので，なくす
　→　トークンがないために発生するエラー文　マシな表示に変える
デモの用のプロジェクトを作成して，表示される内容はすべて英語でにする（日本語）
日付直す
