### ISSUE TITLE
Demo task 1

### ISSUE THREAD

**Issue by yhzz** [lamact/react-issue-ganttchart#55]
```yaml
start_date: 2021/4/18
due_date: 2021/4/18
progress: 0
parent: 69
```
