### ISSUE TITLE
モバイルでも見れるようにする

### ISSUE THREAD

**Issue by jtky8238** [lamact/react-issue-ganttchart#63]
```yaml
start_date: 2021/4/26
due_date: 2021/5/2
progress: 0
parent: 0
```
gannttの左枠 columnsを非表示にできるようにする．
