### ISSUE TITLE
Demotask2

### ISSUE THREAD

**Issue by jtky8238** [lamact/react-issue-ganttchart#69]
```yaml
start_date: 2021/5/16
due_date: 2021/5/16
progress: 0.1
parent: 55
```
