### ISSUE TITLE
asdfasdf

### ISSUE THREAD

**Issue by nervLv32** [lamact/react-issue-ganttchart#80]
```yaml
start_date: 2022/5/22
due_date: 2022/5/22
progress: 0.1
parent: 65
```
