### ISSUE TITLE
aaaa

### ISSUE THREAD

**Issue by amemiya3** [lamact/react-issue-ganttchart#82]
```yaml
start_date: 2022/6/20
due_date: 2022/6/23
progress: 0.1
parent: 0
```
