### ISSUE TITLE
bbb

### ISSUE THREAD

**Issue by amemiya3** [lamact/react-issue-ganttchart#83]
```yaml
start_date: 2022/6/23
due_date: 2022/6/23
progress: 0.1
parent: 82
```
